language: android
sudo: false
jdk:
  - oraclejdk8

android:
  components:
    - tools
    - build-tools-28.0.0
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-x86-android-26
    - sys-img-armeabi-v7a-android-17
licenses:
    - 'android-sdk-license-.+'

before_install:
  - yes | sdkmanager "platforms;android-28"