language: android
sudo: false
jdk: oraclejdk8

android:
  components:
    - tools
    - build-tools-28.0.0
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-x86_64-google_apis_playstore-28
licenses:
    - 'android-sdk-license-.+'

before_install:
  - yes | sdkmanager "platforms;android-28"

script:
  - "./gradlew clean test build"