language: android

jdk:
  - oraclejdk9

android:
  components:
    - tools
    - build-tools-28.0.0
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
licenses:
    - 'android-sdk-license-.+'

before_install:
  - yes | sdkmanager "platforms;android-28"